"""add_test_data_2

Revision ID: a11a51ff51a2
Revises: 2c15b82c3631
Create Date: 2023-09-11 13:35:20.030576

"""
from typing import Sequence, Union
from app.models import User, Tweet
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a11a51ff51a2'
down_revision: Union[str, None] = '2c15b82c3631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add test data to the 'users' table
    op.bulk_insert(User.__table__, [
        {'name': 'User1', 'user_api_key': 'key1'},
        {'name': 'User2', 'user_api_key': 'key2'},

    ])

    op.bulk_insert(Tweet.__table__, [
        {'content': 'Test tweet 1', 'author': 1},
        {'content': 'Test tweet 2', 'author': 2},

    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
